name: todo_app
description: "TODO application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  meta: ^1.16.0
  uuid: ^4.5.1
  flutter_native_splash: ^2.4.4
  flutter_slidable: ^4.0.0
  auto_route: ^9.3.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  intl: ^0.20.2
  flutter_svg: ^2.0.17
  sembast: ^3.8.4
  dio: ^5.8.0
  get_it: ^8.0.3
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  auto_route_generator: ^9.3.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/lottie_animation/

  fonts:

    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/sfProDisplay/thin.otf
          weight: 100
        - asset: assets/fonts/sfProDisplay/regular.otf
          weight: 400
        - asset: assets/fonts/sfProDisplay/semiBold.otf
          weight: 600
        - asset: assets/fonts/sfProDisplay/bold.otf
          weight: 700

    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/sfProText/regular.ttf
          weight: 400
        - asset: assets/fonts/sfProText/semiBold.ttf
          weight: 600
        - asset: assets/fonts/sfProText/bold.ttf
          weight: 700

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/robotoMono/regular.ttf
        - asset: assets/fonts/robotoMono/regular_italic.ttf
          style: italic
        - asset: assets/fonts/robotoMono/medium.ttf
          weight: 500
        - asset: assets/fonts/robotoMono/bold.ttf
          weight: 700

    - family: Lato
      fonts:
        - asset: assets/fonts/lato/bold.ttf
          weight: 700
        - asset: assets/fonts/lato/bold_italic.ttf
          weight: 700
          style: italic
