name: todo_app
description: "TODO application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
    
  flutter_slidable: ^4.0.0

  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.7
  meta: ^1.15.0
  bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/lottie_animation/

  fonts:

    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/sfProDisplay/thin.otf
          weight: 100
        - asset: assets/fonts/sfProDisplay/regular.otf
          weight: 400
        - asset: assets/fonts/sfProDisplay/semiBold.otf
          weight: 600
        - asset: assets/fonts/sfProDisplay/bold.otf
          weight: 700

    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/sfProText/regular.ttf
          weight: 400
        - asset: assets/fonts/sfProText/semiBold.ttf
          weight: 600
        - asset: assets/fonts/sfProText/bold.ttf
          weight: 700

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/robotoMono/regular.ttf
        - asset: assets/fonts/robotoMono/regular_italic.ttf
          style: italic
        - asset: assets/fonts/robotoMono/medium.ttf
          weight: 500
        - asset: assets/fonts/robotoMono/bold.ttf
          weight: 700

    - family: Lato
      fonts:
        - asset: assets/fonts/lato/bold.ttf
          weight: 700
        - asset: assets/fonts/lato/bold_italic.ttf
          weight: 700
          style: italic
